name: Run the data queue alert every 30 mins
on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.3.2'
      
      - name: Setup R dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::httr
            any::xml2
            any::jsonlite
            any::dplyr
            any::janitor
            any::purrr
            any::lubridate
            any::stringr
            any::telegram.bot
      
      - name: Run R script
        env:
          API_URL: ${{ secrets.API_URL }}
          API_USER: ${{ secrets.HEALTH_SMART_CONNECT_USER_NAME }}
          API_PASS: ${{ secrets.HEALTH_SMART_CONNECT_PASSWORD }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        run: Rscript function_data_queue_alert_wetlands_ranger_data_newer.R
        
      - name: Commit updated data
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add past_data_in_queue.csv
          git diff --quiet && git diff --staged --quiet || git commit -m "Update queue data"
          git push